---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # hosts: where our play will run and options it will run with
  hosts: linux
  gather_facts: True

  # vars: variables that will apply to the play, on all target systems
  vars_files:
    - vars/logos.yaml
    
  # Tasks: the list of tasks that will be executed within the play, this section
  tasks:

    - name: Installing Nginx CentOS
      ansible.builtin.yum: 
        name: 
          - epel-release
          - nginx
        state: latest
        update_cache: yes
      when: ansible_distribution == 'CentOS'

    - name: Installing Nginx Ubuntu
      ansible.builtin.apt: 
        name: nginx
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Restart service nginx on all
      ansible.builtin.service:
        name: nginx
        state: restarted
      notify: Check the HTTP Service

    - name: Installing Nginx on all hosts
      ansible.builtin.package: 
        name: unzip
        state: latest
    
    - name: unarchive 
      ansible.builtin.unarchive:
        src: playbook_stacker.zip
        dest: "{{nginx_root_location}}"
        mode: 0755

      #ansible_managed(refer to ansible.cfg) used with ansible templating - The ansible_managed string can be inserted into files written by Ansible’s config templating system - This string can be helpful to indicate that a file should not be directly edited because Ansible may overwrite the contents of the file.

    - name: Template Jinja2 index.html
      ansible.builtin.template:
        src: index.html-easter_egg.j2
        dest: "{{nginx_root_location}}/index.html"
        mode: 0644

  # can also be used for pre and post tasks

  # Handlers: the list of handlers that are executed as a notify key from a task
  handlers:
    - name: Check the HTTP Service
      ansible.builtin.uri:
        url: http://{{ansible_default_ipv4.address}}
        status_code: 200

# Three dots indicate the end of a YAML document
...

